### ISSUE TITLE
Add the plugin to extensions.joomla.org

### ISSUE THREAD

**Issue by ZerooCool** [rebootl/plg_search_mediawiki#3]
Hello,
I've been looking for this plugin for a long time, for Mediawiki and Joomla integrated search.
A Joomla collaborator told me your plugin.

I did not find it in the official extensions for Joomla, on the site https://extensions.joomla.org

Maybe you can make the proposal to add it?

**Comment by ZerooCool** [comment]
Up.
I can't found this extension with extensions.joomla.org

**Comment by rebootl** [comment]
Thx for your feedback. :)
I have made some required adaptions and submitted a request to the JED.
Lez hope it'll work...
