### ISSUE TITLE
Make Joomla intégration Better with search engine.

### ISSUE THREAD

**Issue by ZerooCool** [rebootl/plg_search_mediawiki#6]
Hello. This is your tool that allowed me to integrate the search on Mediawiki from Joomla. Thank you.

At random, I'm looking for the same thing for Redmine, and, again, I can not find it.

If you have the time, the know-how, or, colleagues to propose the development of a search plugin, to link Joomla to Redmine, it would be great.

Note : 
I have only found this module for Redmine and Joomla.
https://extensions.joomla.org/extensions/extension/miscellaneous/misc-bridges/easyredmine-listing/

**Comment by rebootl** [comment]
Hello, thx for your request. Currently I don't have the capacity to do such a thing.
If you were interested in requesting an offer for the payed development of a plugin, you could drop us a mail at empfang@revamp-it.ch .
Thx
