### ISSUE TITLE
Got error 'PHP message: PHP Notice:  Undefined variable: search_expr_esc

### ISSUE THREAD

**Issue by ZerooCool** [rebootl/plg_search_mediawiki#7]
Got error 'PHP message: PHP Notice:  Undefined variable: search_expr_esc in /var/www/domain.ext/plugins/search/mediawiki/mediawiki.php

Line 172

`$search_expr_esc .= "+".$word_esc." ";`

**Comment by ZerooCool** [comment]
https://github.com/rebootl/plg_search_mediawiki/pull/8

**Comment by rebootl** [comment]
hello thx for the report, see comment in the pull req.

**Comment by ZerooCool** [comment]
Up.

You can test with my website : https://www.visionduweb.fr/outils/chercher
